fetch('/api/dataentities/CL/schemas/al-form', {
  headers: { 'Content-Type': 'application/json' },
  method: 'PUT',
  dataType: 'json',
  contentType: 'application/json',
  body: JSON.stringify({
    title: 'Cliente',
    type: 'object',
    properties: {
      corporateName: {
        type: 'string',
        maxLength: 750,
        title: 'Razão Social',
      },
      email: { type: 'string', format: 'email', title: 'Email' },
      corporateDocument: {
        type: 'string',
        maxLength: 50,
        title: 'CNPJ',
      },
      birthDateMonth: { type: 'integer', title: 'Mês de aniversário' },
      document: { type: 'string', maxLength: 50, title: 'Documento' },
      homePhone: { type: 'string', title: 'Telefone Residencial' },
      firstName: { type: 'string', maxLength: 750, title: 'Nome' },
      phone: { type: 'string', title: 'Telefone' },
      userId: {
        type: 'string',
        maxLength: 50,
        title: 'Id do usuário',
      },
      stateRegistration: {
        type: 'string',
        maxLength: 750,
        title: 'Inscrição Estadual',
      },
      customerClass: {
        type: 'string',
        maxLength: 750,
        title: 'CustomerClass',
      },
      gender: { type: 'string', maxLength: 50, title: 'Sexo' },
      isNewsletterOptIn: {
        type: 'boolean',
        title: 'Recebe Newsletter?',
      },
      lastName: {
        type: 'string',
        maxLength: 750,
        title: 'Sobrenome',
      },
      birthDate: {
        type: 'string',
        format: 'date-time',
        title: 'Data de nascimento',
      },
      approved: { type: 'boolean', title: 'Aprovado' },
      tradeName: {
        type: 'string',
        maxLength: 750,
        title: 'Nome Fantasia',
      },
      isCorporate: { type: 'boolean', title: 'É Empresa?' },
      documentType: {
        type: 'string',
        maxLength: 50,
        title: 'Tipo documento',
      },
      businessPhone: {
        type: 'string',
        maxLength: 100,
        title: 'Telefone Comercial',
      },
      priceTables: {
        type: 'string',
        maxLength: 750,
        title: 'Price Tables',
      },
      priceTables: {
        type: 'string',
        maxLength: 750,
        title: 'Price Tables',
      },
      interestTopics: {
        type: 'string',
        maxLength: 50,
        title: 'Tópicos de Interesse',
      },
      financialInfo: {
        type: 'string',
        title: 'Relações comerciais de fornecedores',
      },
    },
    required: ['email', 'id'],
    'v-indexed': [
      'approved',
      'email',
      'brandVisitedTag',
      'categoryVisitedTag',
      'departmentVisitedTag',
      'productVisitedTag',
      'userId',
      'firstName',
      'lastName',
      'document',
      'isNewsletterOptIn',
      'priceTables',
    ],
    'v-security': {
      allowGetAll: false,
      publicJsonSchema: true,
      publicRead: ['id', 'email'],
      publicWrite: [
        'approved',
        'email',
        'corporateDocument',
        'stateRegistration',
        'corporateName',
        'tradeName',
        'document',
        'firstName',
        'lastName',
        'businessPhone',
        'homePhone',
        'isNewsletterOptIn',
        'isCorporate',
        'priceTables',
        'interestTopics',
        'financialInfo',
      ],
      publicFilter: ['email'],
    },
  }),
})
